site_name: OmegaConf Plugin - Cloud Resolvers

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.path
    - toc.follow
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
            ignore_init_summary: false
          merge_init_into_class: false
      default_handler: python
  - search
  - tags:
      tags_file: tags.md


site_url: 'https://mgvalverde.github.io/omegaconf-cloud-resolvers/'  # Trailing slash is recommended
repo_url: https://github.com/mgvalverde/omegaconf-cloud-resolvers
#repo_name: omegaconf-cloud-resolvers  # hidden; too long

extra:
  version:
    provider: mike

nav:
  - Welcome: index.md
  - Installation: first/install.md
  - Usage:
      - Quickstart:
          - Introduction to OmegaConf: users-guide/quickstart.md
          - Cloud Resolvers: users-guide/resolvers.md
      - Integration with Hydra: users-guide/integration-hydra.md
  - References:
      - Register Custom Resolvers: api/register.md
      - Resolvers:
          - AWS:
              - Parameter Store: api/resolvers/aws/parameterstore.md
              - Secrets Manager: api/resolvers/aws/secretsmanager.md
          - GCP:
              - Secret Manager: api/resolvers/gcp/secretmanager.md
  - Tags: tags.md